esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 40000000L
    board_build.flash_size: 4MB

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    advanced:
      ignore_efuse_mac_crc: false

spi:
- id: spi_0
  mosi_pin: GPIO6
  clk_pin: GPIO4

i2c:
- id: i2c_0
  sda: GPIO8
  scl: GPIO9
  scan: true
